services:
  valheim:
    image: ${REPO_NAME}/valheim:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${REPO_NAME}/${BASE_IMAGE}
    ports:
      - "${PORT_RANGE}:${PORT_RANGE}/udp"
      - "${PORT_RANGE}:${PORT_RANGE}/tcp"
    volumes:
      - /gameservermounts/${CONTAINER_NAME}:/home/valheim/.config/unity3d/IronGate/Valheim/worlds
    restart: unless-stopped
