services:
  dragonwilds:
    image: ${REPO_NAME}/dragonwilds:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${REPO_NAME}/${BASE_IMAGE}
        - SERVER_ID=${SERVER_ID}
        - SERVER_NAME=${SERVER_NAME}
        - SERVER_ADMIN_PASSWORD=${SERVER_ADMIN_PASSWORD}
        - SERVER_OWNER_ID=${SERVER_OWNER_ID}
        - WORLD_NAME=${WORLD_NAME}
        - WORLD_PASSWORD=${WORLD_PASSWORD}
        - SERVER_PORT_RANGE=${PORT_RANGE}
      tags:
        - latest
        - ${VERSION_TAG}
    ports:
      - "${PORT_RANGE}:${PORT_RANGE}/udp"
      - "${PORT_RANGE}:${PORT_RANGE}/tcp"
    volumes:
      - ${LOCAL_MOUNT_PATH}/${CONTAINER_NAME}:/opt/dragonwildsserver/RSDragonwilds/Saved
    restart: unless-stopped

