services:
  dragonwilds:
    image: ${REPO_NAME}/dragonwilds:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${REPO_NAME}/${BASE_IMAGE}
      tags:
        - latest
        - ${VERSION_TAG}
    ports:
      - "${PORT_RANGE}:${PORT_RANGE}/udp"
      - "${PORT_RANGE}:${PORT_RANGE}/tcp"
    volumes:
      - /gameservermounts/${CONTAINER_NAME}:/opt/dragonwildsserver/RSDragonwilds/Saved
    restart: unless-stopped

