;METADATA=(Diff=true, UseCommands=true)
[/Script/Dominion.DedicatedServerSettings]
AdminPassword=
#Steam ID of the server owner.
OwnerId=
#Format: F7E97AFA381D4E7D886908407EB86D69
ServerGuid= 
ServerName=
WorldPassword=
DefaultWorldName=